aws_region           = "ap-northeast-1"
api_name             = "pillow-api"
lambda_function_name = "pillow-lambda"
source_dir           = "./src/"
bucket_name          = "elonniu"
app_stage            = "dev"
