aws_region           = "us-west-2"
provider_role_arn    = "arn:aws:iam::424767991975:role/serverless-tf-resource-role-test"
api_name             = "pillow-api"
lambda_function_name = "pillow-lambda"
source_dir           = "./src/"
