aws_region           = "ap-northeast-1"
api_name             = "pillow-api-debug"
lambda_function_name = "pillow-lambda-debug"
source_dir           = "./src/"
image_bucket         = "elonniu"
app_stage            = "dev"
